title: "Brik's Blog"
author: "Brik"
description: "A minimal Jekyll blog"
baseurl: "/blogs"  # This should match your repository name
url: "https://brikjr.github.io"

markdown: kramdown
permalink: /:year/:month/:day/:title

exclude: 
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - admin/